import fs from "fs";
import path from "path";
import chalk from "chalk";
import {
  specletPath,
  writeSpecletFile,
  slugify,
  loadPlanFiles,
} from "../utils.js";

const AGENTS = ["all", "claude", "copilot", "cursor", "vibe", "commandcode", "antigravity"] as const;
type Agent = (typeof AGENTS)[number];

export async function initCommand(planPath: string | undefined, opts: { agent: string }) {
  const agent = opts.agent as Agent;

  // --- Load plan files if provided ---
  let phases: Array<{ heading: string; content: string; sourceFile: string }> = [];
  let sourceFiles: string[] = [];

  if (planPath) {
    try {
      phases = loadPlanFiles(planPath);
    } catch (err: any) {
      console.error(chalk.red(`✖ ${err.message}`));
      process.exit(1);
    }

    if (phases.length === 0) {
      console.log(
        chalk.yellow(`⚠ No phases detected in ${chalk.cyan(planPath)}.\n`) +
        chalk.dim(`  Add ## headings to define phases:\n`) +
        chalk.dim(`  ## Phase 1: Setup\n`) +
        chalk.dim(`  ## Phase 2: Core Features\n`)
      );
    } else {
      sourceFiles = [...new Set(phases.map((p) => p.sourceFile))];
      console.log(
        chalk.dim(`Found ${phases.length} phase(s) across ${sourceFiles.length} file(s):`) +
        sourceFiles.map((f) => `\n  ${chalk.cyan(f)}`).join("")
      );
      console.log();
    }
  } else {
    console.log(chalk.dim(`No plan path given — scaffolding .speclet/ templates only.`));
    console.log(chalk.dim(`Use /speclet-plan in your AI agent to create plan files, or "speclet map" for existing projects.\n`));
  }

  // --- Create .speclet dir ---
  const specletDir = specletPath();
  if (fs.existsSync(specletDir)) {
    console.log(chalk.yellow(`⚠ .speclet already exists — re-initializing.`));
  }
  fs.mkdirSync(specletPath("tasks"), { recursive: true });
  fs.mkdirSync(specletPath("prompts"), { recursive: true });

  // --- Copy plan files into .speclet/plans/ ---
  if (planPath && sourceFiles.length > 0) {
    fs.mkdirSync(specletPath("plans"), { recursive: true });
    const resolved = path.resolve(process.cwd(), planPath);
    const isFolder = fs.statSync(resolved).isDirectory();
    if (isFolder) {
      for (const srcFile of sourceFiles) {
        const content = fs.readFileSync(path.resolve(process.cwd(), srcFile), "utf-8");
        writeSpecletFile(content, "plans", path.basename(srcFile));
        console.log(chalk.green(`✔ Copied ${srcFile} → .speclet/plans/${path.basename(srcFile)}`));
      }
    } else {
      const content = fs.readFileSync(resolved, "utf-8");
      writeSpecletFile(content, "plans", path.basename(planPath));
      console.log(chalk.green(`✔ Copied ${planPath} → .speclet/plans/${path.basename(planPath)}`));
    }
  }

  // --- Write context.md ---
  if (!fs.existsSync(specletPath("context.md"))) {
    writeSpecletFile(contextTemplate(), "context.md");
    console.log(chalk.green(`✔ Created .speclet/context.md`) + chalk.dim(` (edit with your stack & conventions)`));
  } else {
    console.log(chalk.dim(`  Kept existing .speclet/context.md`));
  }

  // --- Scaffold constitution.md if missing ---
  if (!fs.existsSync(specletPath("constitution.md"))) {
    writeSpecletFile(constitutionTemplate(), "constitution.md");
    console.log(
      chalk.green(`✔ Created .speclet/constitution.md`) +
      chalk.dim(` (run "speclet constitution" to fill it in)`)
    );
  } else {
    console.log(chalk.dim(`  Kept existing .speclet/constitution.md`));
  }

  // --- Scaffold constitution.learned.md if missing ---
  if (!fs.existsSync(specletPath("constitution.learned.md"))) {
    writeSpecletFile(learnedConstitutionTemplate(), "constitution.learned.md");
    console.log(chalk.green(`✔ Created .speclet/constitution.learned.md`) + chalk.dim(` (auto-filled during implementation)`));
  } else {
    console.log(chalk.dim(`  Kept existing .speclet/constitution.learned.md`));
  }

  // --- Write tasks/index.md (phase map only — no task files yet) ---
  if (phases.length > 0) {
    const indexLines = [
      `# Task Index`,
      ``,
      `> Auto-generated by speclet. Run "speclet tasks" to generate phase files.`,
      ``,
      `## Phases`,
      ``,
      ...phases.map((p, i) => {
        const slug = slugify(p.heading);
        const file = `tasks/phase-${i + 1}-${slug}.md`;
        return `- **${p.heading}** → \`${file}\` _(source: ${p.sourceFile})_`;
      }),
    ];
    writeSpecletFile(indexLines.join("\n"), "tasks", "index.md");
    console.log(chalk.green(`✔ Created .speclet/tasks/index.md`) + chalk.dim(` (${phases.length} phase(s) mapped, no task files yet)`));
  } else {
    // Write a placeholder index so the directory is not empty
    if (!fs.existsSync(specletPath("tasks", "index.md"))) {
      writeSpecletFile(
        `# Task Index\n\n> Use /speclet-plan in your AI agent to create plan files or "speclet map" for existing projects. No phases registered yet.\n`,
        "tasks", "index.md"
      );
      console.log(chalk.dim(`  Created placeholder .speclet/tasks/index.md`));
    }
  }

  // --- Write prompt templates ---
  writeSpecletFile(planPrompt(), "prompts", "plan.md");
  writeSpecletFile(clarifyPrompt(), "prompts", "clarify.md");
  writeSpecletFile(analyzePrompt(), "prompts", "analyze.md");
  writeSpecletFile(tasksPrompt(), "prompts", "tasks.md");
  writeSpecletFile(implementPrompt(), "prompts", "implement.md");
  writeSpecletFile(constitutionPrompt(), "prompts", "constitution.md");
  writeSpecletFile(learnPrompt(), "prompts", "learn.md");
  console.log(chalk.green(`✔ Created .speclet/prompts/`));

  // --- Agent files ---
  scaffoldAgent(agent);

  const agentLabel = agent === "all" ? "all agents" : agent;
  console.log(
    `\n${chalk.bold("speclet initialized")} — ${chalk.cyan(phases.length)} phase(s) from ${chalk.cyan(sourceFiles.length)} file(s), agent: ${chalk.cyan(agentLabel)}\n` +
    (phases.length > 0
      ? `\n${chalk.dim("Next steps:")}\n` +
        `  1. Edit ${chalk.cyan(".speclet/context.md")} with your stack & conventions\n` +
        `  2. Run ${chalk.cyan("speclet constitution")} (or use ${chalk.cyan("/speclet-constitution")} in your agent) to set ground rules\n` +
        `  3. Run ${chalk.cyan("speclet tasks")} (or use ${chalk.cyan("/speclet-tasks")} in your agent) to generate tasks\n` +
        `  4. Run ${chalk.cyan("speclet implement <phase>")} (or use ${chalk.cyan("/speclet-implement <phase>")}) to start building\n`
      : `\n${chalk.dim("Next steps:")}\n` +
        `  1. Use ${chalk.cyan("/speclet-plan")} in your AI agent to create plan files interactively\n` +
        `  2. Run ${chalk.cyan("speclet map")} if you have an existing codebase to scan\n` +
        `  3. Edit ${chalk.cyan(".speclet/context.md")} with your stack & conventions\n` +
        `  4. Run ${chalk.cyan("speclet init ./plans")} once you have plan files ready\n`
    )
  );
}

// ─── Agent scaffolding ────────────────────────────────────────────────────────

function scaffoldAgent(agent: string) {
  const targets = agent === "all" ? ["claude", "copilot", "cursor", "vibe", "commandcode", "antigravity"] : [agent];
  for (const t of targets) scaffoldSingleAgent(t);
}

function scaffoldSingleAgent(agent: string) {
  const cwd = process.cwd();

  if (agent === "claude") {
    const commandsDir = path.join(cwd, ".claude", "commands");
    fs.mkdirSync(commandsDir, { recursive: true });

    const commands: Record<string, string> = {
      "speclet-plan.md": claudeCmd(
        "plan",
        `Act as a senior system architect / lead engineer and help the developer turn an idea into a phased plan, written to \`.speclet/plans/\`.

Topic (optional): $ARGUMENTS

Core behaviour:
- **Propose, do not decide.** For every meaningful decision (architecture, tech choices, phase boundaries, ordering, scope) present 2–4 concrete options with trade-offs, recommend the one you'd pick and why — but the developer makes the final call.
- **Always ask, never assume.** When anything is unclear or could go more than one way, ask. Invite the developer's own ideas: "pick one, or tell me your own approach."
- **One question at a time** — wait for each answer before continuing.

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present and filled in). If \`.speclet/architecture.md\` or existing \`.speclet/plans/\` files exist, read them too.
2. Interview the developer through: scope → architecture approach → phase breakdown → dependencies/ordering → file structure.
3. Once decisions are confirmed, write the plan file(s) to \`.speclet/plans/\` — one \`##\` heading per phase (no tasks yet).
4. Follow the instructions in \`.speclet/prompts/plan.md\` step by step. Suggest \`/speclet-tasks\` as the next step.`
      ),
      "speclet-map.md": claudeCmd(
        "map",
        `Perform a full retroactive speclet setup of an existing codebase.

This command produces every speclet file as if speclet had been used from the start, with all existing work documented and marked done so new features can be planned immediately.

Files to produce:
- \`.speclet/context.md\` — real stack, conventions, module structure, constraints
- \`.speclet/architecture.md\` — module map, key files, data flow, integrations, tech debt
- \`.speclet/constitution.md\` — ground rules inferred from lint config, patterns, test setup, CI
- \`.speclet/plans/01-existing.md\` — plan file with \`##\` phases describing what was built
- \`.speclet/tasks/index.md\` — phase map
- \`.speclet/tasks/phase-N-*.md\` — one task file per phase, all tasks marked \`[x]\` done

Follow the instructions in \`.speclet/prompts/map.md\` step by step.`
      ),
      "speclet-constitution.md": claudeCmd(
        "constitution",
        `Fill in the project constitution.

1. Read \`.speclet/context.md\` to understand the project stack.
2. Read \`.speclet/constitution.md\` (current state).
3. Follow the instructions in \`.speclet/prompts/constitution.md\` — ask the developer questions section by section and write the answers back into \`.speclet/constitution.md\`.`
      ),
      "speclet-clarify.md": claudeCmd(
        "clarify",
        `Generate clarifying questions about the plan or a specific phase.

Phase (optional): $ARGUMENTS

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present and filled in).
2. If a phase number or name was given in $ARGUMENTS, read only that phase file from \`.speclet/tasks/\`.
   Otherwise read the plan files in \`.speclet/plans/\`.
3. Follow the instructions in \`.speclet/prompts/clarify.md\`.`
      ),
      "speclet-analyze.md": claudeCmd(
        "analyze",
        `Analyze tasks for gaps, conflicts, and risks, then update task files and implement fixes.

Phase (optional): $ARGUMENTS

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present and filled in).
2. Read \`.speclet/tasks/index.md\`.
3. If a phase number or name was given in $ARGUMENTS, load only that phase file.
   Otherwise load each phase file one at a time — do not load all at once.
4. **Run the analysis first**. If a follow-up instruction was provided:
   a. Update affected task/phase files to reflect needed changes FIRST.
   b. Then implement the described code changes.
   Task files must stay in sync as the source of truth.
5. Follow the instructions in \`.speclet/prompts/analyze.md\`.`
      ),
      "speclet-tasks.md": claudeCmd(
        "tasks",
        `Generate concrete tasks for a plan phase and write them to the phase file.

Phase (optional): $ARGUMENTS

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present and filled in).
2. Read \`.speclet/tasks/index.md\` to see the phase map.
3. If a phase number or name was given in $ARGUMENTS, process only that phase.
   Otherwise process all phases one at a time — never load all phase files at once.
4. For each phase, load its plan content from \`.speclet/plans/\`, generate tasks, and write them to the task file listed in the index.
5. Follow the instructions in \`.speclet/prompts/tasks.md\`.`
      ),
      "speclet-implement.md": claudeCmd(
        "implement",
        `Implement all tasks in a single phase, marking each done as you go.

Phase (required): $ARGUMENTS

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present and filled in).
2. If \`.speclet/constitution.learned.md\` exists, read it — follow rules in the ## Pending Rules section.
3. Read \`.speclet/tasks/index.md\` to find the phase file.
4. Resolve the phase from $ARGUMENTS by number or name.
5. Load ONLY that phase file — do not load any other phase files.
6. Work through each unchecked task \`- [ ]\` in order: implement it, then mark it \`- [x]\`.
7. Follow the instructions in \`.speclet/prompts/implement.md\`.
8. If any rules were written to \`.speclet/constitution.learned.md\`, mention them at the end and suggest running /project:speclet-learn.`
      ),
      "speclet-learn.md": claudeCmd(
        "learn",
        `Review auto-captured rules from recent implementation sessions and merge them into the constitution.

1. Read \`.speclet/constitution.learned.md\` — pending rules captured during implementation.
2. Read \`.speclet/constitution.md\` — the current permanent ground rules.
3. Present each pending rule one at a time and ask: Keep, Skip, or Defer?
   Wait for the answer before moving to the next.
4. Follow the instructions in \`.speclet/prompts/learn.md\`.`
      ),
    };

    for (const [file, content] of Object.entries(commands)) {
      fs.writeFileSync(path.join(commandsDir, file), content, "utf-8");
    }
    console.log(chalk.green(`✔ Created .claude/commands/ — 8 slash commands`) +
      chalk.dim(` (/project:speclet-plan, /project:speclet-map, /project:speclet-tasks, /project:speclet-implement <phase>, /project:speclet-learn, ...)`));
  }

  if (agent === "cursor") {
    const rulesDir = path.join(cwd, ".cursor", "rules");
    fs.mkdirSync(rulesDir, { recursive: true });
    fs.writeFileSync(path.join(rulesDir, "speclet.mdc"), cursorRules(), "utf-8");
    console.log(chalk.green(`✔ Created .cursor/rules/speclet.mdc`));
  }

  if (agent === "vibe") {
    const vibeDir = path.join(cwd, ".vibe");
    fs.mkdirSync(vibeDir, { recursive: true });

    // AGENTS.md — always-on context for every Vibe session in this project
    const agentsMdFile = path.join(vibeDir, "AGENTS.md");
    const existingAgentsMd = fs.existsSync(agentsMdFile)
      ? fs.readFileSync(agentsMdFile, "utf-8") + "\n\n"
      : "";
    fs.writeFileSync(agentsMdFile, existingAgentsMd + vibeAgentsMd(), "utf-8");

    // Skills — one directory per command, each with a SKILL.md file
    const skillsDir = path.join(vibeDir, "skills");
    const skills: Record<string, string> = {
      "speclet-plan": vibeSkillPlan(),
      "speclet-map": vibeSkillMap(),
      "speclet-constitution": vibeSkillConstitution(),
      "speclet-clarify": vibeSkillClarify(),
      "speclet-analyze": vibeSkillAnalyze(),
      "speclet-tasks": vibeSkillTasks(),
      "speclet-implement": vibeSkillImplement(),
      "speclet-learn": vibeSkillLearn(),
    };
    for (const [skillName, content] of Object.entries(skills)) {
      const skillDir = path.join(skillsDir, skillName);
      fs.mkdirSync(skillDir, { recursive: true });
      fs.writeFileSync(path.join(skillDir, "SKILL.md"), content, "utf-8");
    }

    console.log(chalk.green(`✔ Updated .vibe/AGENTS.md`));
    console.log(chalk.green(`✔ Created .vibe/skills/ — 8 skill files`) +
      chalk.dim(` (/speclet-plan, /speclet-map, /speclet-tasks, /speclet-implement, /speclet-clarify, /speclet-analyze, /speclet-constitution, /speclet-learn)`));
  }

  if (agent === "copilot") {
    const ghDir = path.join(cwd, ".github");
    fs.mkdirSync(ghDir, { recursive: true });

    // Persistent context for all Copilot Chat sessions
    const instrFile = path.join(ghDir, "copilot-instructions.md");
    const existing = fs.existsSync(instrFile)
      ? fs.readFileSync(instrFile, "utf-8") + "\n\n"
      : "";
    fs.writeFileSync(instrFile, existing + copilotInstructions(), "utf-8");

    // Agent files — appear in the Copilot Chat agent dropdown as custom agents
    const agentsDir = path.join(ghDir, "agents");
    fs.mkdirSync(agentsDir, { recursive: true });

    const agentFiles: Record<string, string> = {
      "speclet.plan.agent.md": specletPlanAgent(),
      "speclet.map.agent.md": specletMapAgent(),
      "speclet.constitution.agent.md": specletConstitutionAgent(),
      "speclet.tasks.agent.md": specletTasksAgent(),
      "speclet.implement.agent.md": specletImplementAgent(),
      "speclet.clarify.agent.md": specletClarifyAgent(),
      "speclet.analyze.agent.md": specletAnalyzeAgent(),
      "speclet.learn.agent.md": specletLearnAgent(),
    };
    for (const [file, content] of Object.entries(agentFiles)) {
      fs.writeFileSync(path.join(agentsDir, file), content, "utf-8");
    }

    // Prompt files — thin wrappers linking /speclet.X slash commands to agent files
    const promptsDir = path.join(ghDir, "prompts");
    fs.mkdirSync(promptsDir, { recursive: true });

    for (const name of ["plan", "constitution", "tasks", "implement", "clarify", "analyze", "learn"]) {
      fs.writeFileSync(
        path.join(promptsDir, `speclet.${name}.prompt.md`),
        `---\nagent: speclet.${name}\n---\n`,
        "utf-8"
      );
    }
    // map prompt — also add this shortcut
    fs.writeFileSync(
      path.join(promptsDir, `speclet.map.prompt.md`),
      `---\nagent: speclet.map\n---\n`,
      "utf-8"
    );

    console.log(chalk.green(`✔ Updated .github/copilot-instructions.md`));
    console.log(chalk.green(`✔ Created .github/agents/ — 8 agent files`) +
      chalk.dim(` (appear in Copilot Chat agent dropdown)`));
    console.log(chalk.green(`✔ Created .github/prompts/ — 8 prompt files`) +
      chalk.dim(` (/speclet.plan, /speclet.map, /speclet.tasks, /speclet.implement, /speclet.clarify, /speclet.analyze, /speclet.constitution, /speclet.learn)`));
  }

  if (agent === "commandcode") {
    const ccSkillsDir = path.join(cwd, ".commandcode", "skills");
    const skills: Record<string, string> = {
      "speclet-plan": ccSkillPlan(),
      "speclet-map": ccSkillMap(),
      "speclet-constitution": ccSkillConstitution(),
      "speclet-clarify": ccSkillClarify(),
      "speclet-analyze": ccSkillAnalyze(),
      "speclet-tasks": ccSkillTasks(),
      "speclet-implement": ccSkillImplement(),
      "speclet-learn": ccSkillLearn(),
    };
    for (const [skillName, content] of Object.entries(skills)) {
      const skillDir = path.join(ccSkillsDir, skillName);
      fs.mkdirSync(skillDir, { recursive: true });
      fs.writeFileSync(path.join(skillDir, "SKILL.md"), content, "utf-8");
    }
    console.log(chalk.green(`✔ Created .commandcode/skills/ — 8 skill files`) +
      chalk.dim(` (/speclet-plan, /speclet-map, /speclet-tasks, /speclet-implement, /speclet-clarify, /speclet-analyze, /speclet-constitution, /speclet-learn)`));
  }

  if (agent === "antigravity") {
    const agSkillsDir = path.join(cwd, ".agents", "skills");
    const skills: Record<string, string> = {
      "speclet-plan": ccSkillPlan(),
      "speclet-map": ccSkillMap(),
      "speclet-constitution": ccSkillConstitution(),
      "speclet-clarify": ccSkillClarify(),
      "speclet-analyze": ccSkillAnalyze(),
      "speclet-tasks": ccSkillTasks(),
      "speclet-implement": ccSkillImplement(),
      "speclet-learn": ccSkillLearn(),
    };
    for (const [skillName, content] of Object.entries(skills)) {
      const skillDir = path.join(agSkillsDir, skillName);
      fs.mkdirSync(skillDir, { recursive: true });
      fs.writeFileSync(path.join(skillDir, "SKILL.md"), content, "utf-8");
    }
    console.log(chalk.green(`✔ Created .agents/skills/ — 8 skill files`) +
      chalk.dim(` (/speclet-plan, /speclet-map, /speclet-tasks, /speclet-implement, /speclet-clarify, /speclet-analyze, /speclet-constitution, /speclet-learn)`));
  }
}

// ─── Templates ────────────────────────────────────────────────────────────────

function contextTemplate(): string {
  return `# Project Context

> Keep this file minimal. It is injected into every speclet prompt.

## Stack
- Language: 
- Framework: 
- Database: 
- Deployment: 

## Conventions
- 
- 

## Constraints
- 
`;
}

function constitutionTemplate(): string {
  return `# Project Constitution

<!-- speclet:unfilled -->
<!-- Run "speclet constitution" to fill this in with your AI agent. -->
<!-- Delete the two lines above once you've filled this in.     -->

> Ground rules for this project. Injected into every speclet prompt once filled in.

## Code Quality
-

## Architecture Principles
-

## Testing Requirements
-

## What To Avoid
-

## Definition of Done
A task is done when:
-
`;
}

function learnedConstitutionTemplate(): string {
  return `# Learned Constitution

<!-- speclet:learned -->
> Rules auto-captured during implementation sessions.
> Run "speclet learn" to review and merge rules into constitution.md.

## Pending Rules

<!-- Rules are appended here by the agent during implementation. Format:
### [YYYY-MM-DD] category: short-title
**Rule:** What to always do.
**Why:** What went wrong or why this matters.
-->
`;
}

function learnPrompt(): string {
  return `# Learn Prompt

You are reviewing auto-captured rules from recent implementation sessions and deciding which ones to permanently add to the project constitution.

## Instructions

1. Read \`.speclet/constitution.learned.md\` — pending rules captured during implementation.
2. Read \`.speclet/constitution.md\` — the current permanent ground rules.
3. Present each pending rule to the developer one at a time.
   For each rule, ask: **Keep (merge into constitution), Skip (discard), or Defer (leave for later)?**
   Wait for the answer before moving to the next.

## Merge Rules

- **Keep**: Add the rule to the appropriate section of \`.speclet/constitution.md\`. If no section fits, add a new one.
- **Skip**: Remove the rule from \`.speclet/constitution.learned.md\`.
- **Defer**: Leave the rule in \`.speclet/constitution.learned.md\` unchanged.

## After Processing All Rules

1. Rewrite \`.speclet/constitution.md\` with all kept rules merged in.
2. Rewrite \`.speclet/constitution.learned.md\` with only deferred rules remaining (remove kept and skipped entries).
   If no rules remain, leave the file with its header and an empty \`## Pending Rules\` section.
3. Report: how many rules were merged, skipped, and deferred.
`;
}


function planPrompt(): string {
  return `# Plan Prompt

You are acting as a **senior system architect and lead engineer** helping the developer
turn an idea into a concrete plan **before** any code is written. The output is one or
more markdown plan files in \`.speclet/plans/\`, each broken into phases using \`##\` headings.

## How you must behave

- **Propose, do not decide.** You are an advisor, not the decision-maker. For every
  meaningful decision (architecture, tech choice, phase boundaries, ordering, scope),
  present **2–4 concrete options** with honest trade-offs, then **recommend** the one you
  would pick as a lead engineer and say *why* — but the developer makes the final call.
- **Always ask, never assume.** When anything is unclear, missing, or could go more than
  one way, ask the developer instead of guessing. Invite their own ideas every time:
  "Pick one of these, or tell me if you have a different approach in mind."
- **One question at a time.** Ask a single question, wait for the answer, then continue.
  Do not dump a long questionnaire.
- **Think like an architect.** Surface risks, hidden complexity, dependencies, and
  sequencing concerns the developer may not have considered — framed as suggestions to
  confirm, not as final rulings.

## Before you start

1. Read \`.speclet/context.md\` (stack, conventions, constraints).
2. Read \`.speclet/constitution.md\` if present and filled in (no \`<!-- speclet:unfilled -->\` marker) — respect its ground rules in everything you propose.
3. If \`.speclet/architecture.md\` exists, read it to understand existing modules and boundaries.
4. If \`.speclet/plans/\` already has plan files, read them so you extend rather than duplicate.

## Interview flow (one question at a time, with options + a recommendation)

### 1 — Scope
- **What are you building?** Get a one-line description of the feature/project.
- Reflect it back and confirm what is explicitly **in** and **out** of scope.

### 2 — Architecture approach
- Propose 2–4 candidate approaches (e.g. patterns, data flow, where the work lives),
  each with trade-offs, and recommend one. Ask the developer to choose or propose their own.

### 3 — Phase breakdown
- **What does "done" look like?** The end state when the feature is fully built.
- Suggest a phase breakdown (the logical increments from nothing → done). Recommend
  3–8 phases. For each phase propose a **name** and **key deliverables** (2–4 sentences).
- Ask the developer to confirm, adjust, merge, or split phases. Do NOT generate tasks here —
  tasks come later via \`/speclet-tasks\`.

### 4 — Dependencies & ordering
- Point out which phases depend on others and recommend a build order.
- Flag any phase that could be optional or deferred. Confirm with the developer.

### 5 — File structure
- Recommend where new code should live (e.g. \`src/features/x/\`) and which existing
  modules likely need changes. Confirm with the developer.

## Output

After the developer has confirmed the decisions, write the plan file(s) to \`.speclet/plans/\`:

\`\`\`markdown
# <Feature Name>

> Plan created interactively via /speclet-plan.

## Phase 1: <Name>
<2–4 sentence description of what gets built in this phase>

## Phase 2: <Name>
<Description>

...
\`\`\`

### File naming
- Numbered prefixes for ordering: \`01-backend.md\`, \`02-frontend.md\`, or a single \`01-<feature-slug>.md\`.
- Lowercase, hyphens for spaces.

### Rules
- Each phase = one \`##\` heading with a descriptive name.
- 2–4 sentence description per phase — enough to scope it, not a full spec.
- Phases must be ordered. Keep descriptions high-level — tasks are generated later.
- Only write the files once the developer has signed off on the decisions.

## After writing
- List the files created and confirm the phase count.
- Suggest the next step: \`/speclet-tasks\` to break the phases into concrete tasks.
`;
}

function constitutionPrompt(): string {
  return `# Constitution Prompt

You are helping define the ground rules for this project before development begins.

## Instructions

1. Read \`.speclet/context.md\` to understand the project's stack and constraints.
2. Read the current \`.speclet/constitution.md\`.
3. Ask the developer the following questions one section at a time.
   Wait for answers before moving to the next section.

## Questions to ask

### Code Quality
- What coding standards or style guides should be followed?
- Are there linting or formatting tools to enforce (ESLint, Prettier, etc.)?

### Architecture Principles
- What architectural patterns should be used (e.g. layered, hexagonal, feature-based)?
- Are there any patterns to explicitly avoid?

### Testing Requirements
- What level of test coverage is expected?
- Which types of tests are required (unit, integration, e2e)?
- What testing libraries should be used?

### What To Avoid
- Are there libraries, patterns, or approaches that are off-limits?
- Any security or compliance rules to follow?

### Definition of Done
- What does "done" mean for a task in this project?
- Is there a review or approval process?

## After collecting answers

Rewrite \`.speclet/constitution.md\` with the answers filled in.
Remove the \`<!-- speclet:unfilled -->\` marker line.
Keep the file concise — it will be injected into every future prompt.
`;
}

function clarifyPrompt(): string {
  return `# Clarify Prompt

You are helping clarify a development plan before implementation begins.

## Instructions

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present).
2. If a specific phase was requested, read only that phase file from \`.speclet/tasks/\`.
   Otherwise read the files in \`.speclet/plans/\`.
3. Generate a concise list of clarifying questions grouped by category:
   - **Scope** — what is explicitly in/out?
   - **Technical** — ambiguous implementation decisions
   - **Dependencies** — external services, APIs, or data sources
   - **Edge cases** — scenarios not addressed in the plan

## Output Format

### Clarifying Questions

#### Scope
- [ ] ...

#### Technical
- [ ] ...

#### Dependencies
- [ ] ...

#### Edge Cases
- [ ] ...

Keep questions specific and answerable. Aim for quality over quantity.
`;
}

function analyzePrompt(): string {
  return `# Analyze Prompt

You are reviewing tasks for gaps, conflicts, or risks and then implementing fixes.

**You MUST run the full analysis first**, then handle any follow-up instruction.

## Instructions

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present).
2. Read \`.speclet/tasks/index.md\` to understand the full scope.
3. If analyzing a specific phase, load only that phase file.
   Otherwise load each phase file one at a time — do not load all at once.
4. If a \`<follow-up>\` block is present: run the analysis first, then:
   a. **Update task/phase files FIRST** — add, modify, or remove tasks in affected phase files to reflect needed changes. Create new task files if needed.
   b. **Then implement code changes** — make the actual code edits described by the updated tasks.
   Task files MUST be updated before code changes to keep them in sync as the source of truth.

## Output Format

### Analysis Report

#### Conflicts
Issues where two tasks contradict or overlap each other.
- [ ] **[phase-file]** Description of conflict

#### Gaps
Missing tasks that are implied by the plan but not listed.
- [ ] **[phase-file]** Description of gap

#### Risks
Tasks that are vague, high-effort, or have unclear success criteria.
- [ ] **[phase-file]** Description of risk

#### Suggestions
Optional improvements to task ordering or grouping.
- [ ] ...

If no issues found in a category, write "None found."
`;
}

function tasksPrompt(): string {
  return `# Tasks Prompt

You are breaking a plan phase into concrete, actionable development tasks.

## Instructions

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present).
2. Read \`.speclet/tasks/index.md\` to see which phase files exist.
3. For each phase (or the requested phase only):
   - Load the phase file from \`.speclet/tasks/\`
   - Generate tasks for that phase
   - Write the tasks back into that phase file under the ## Tasks section
   - Do NOT load other phase files while working on one

## Task Format

Each task must be:
- Atomic — one clear unit of work
- Specific — includes enough detail to implement without re-reading the plan
- Ordered — listed in the sequence they should be done

\`\`\`
- [ ] **Task title** — brief description of what to do and what done looks like
\`\`\`

## Rules

- Process one phase file at a time to minimize token usage
- Do not duplicate tasks across phases
- Reference the stack from context.md
- Respect constraints from constitution.md (testing, architecture, quality rules)
`;
}

function implementPrompt(): string {
  return `# Implement Prompt

You are implementing tasks from a single phase file.

## Instructions

1. Read \`.speclet/context.md\` and \`.speclet/constitution.md\` (if present).
2. If \`.speclet/constitution.learned.md\` exists, read it — follow any rules in the \`## Pending Rules\` section.
3. Read \`.speclet/tasks/index.md\` to confirm the phase file location.
4. Load ONLY the requested phase file — do not load other phases.
5. Work through each unchecked task \`- [ ]\` in order:
   - Implement the task
   - Mark it done: \`- [x]\`
   - Move to the next

## Rules

- Follow the stack and conventions in context.md exactly
- Honour the quality rules, architecture principles, and DoD from constitution.md
- If a task is ambiguous, add a comment in the code and note it — do not guess
- Do not modify other phase files
- When all tasks in the phase are done, summarize what was built

## Capturing Learned Rules

While implementing, if you:
- Correct a bash command (add a missing flag, fix a path, switch tools)
- Discover a project-specific pattern not in the constitution
- Notice something that should always be done to avoid a mistake

→ Append the rule to \`.speclet/constitution.learned.md\` under \`## Pending Rules\`:

\`\`\`
### [YYYY-MM-DD] category: short-title
**Rule:** What to always do.
**Why:** What went wrong or why this matters.
\`\`\`

Categories: \`bash\`, \`pattern\`, \`architecture\`, \`testing\`, \`tooling\`

## On Completion

1. Update the phase file header with:
\`\`\`
Status: Complete
Completed: <date>
\`\`\`
2. If you added any rules to \`.speclet/constitution.learned.md\`, mention them and suggest the user run \`speclet learn\` to review and merge them.
`;
}

function claudeCmd(name: string, instructions: string): string {
  return `# speclet ${name}\n\n${instructions}\n`;
}

// ─── Copilot agent files ───────────────────────────────────────────────────────

function specletPlanAgent(): string {
  return `---
description: Act as a senior system architect / lead engineer and help the developer turn an idea into a phased plan — proposing options with trade-offs and letting the developer decide.
handoffs:
  - label: Clarify the Plan
    agent: speclet.clarify
    prompt: Surface ambiguities and open questions in the plan we just created
    send: true
  - label: Generate Tasks
    agent: speclet.tasks
    prompt: Generate tasks for the phases we just planned
    send: true
---

## User Input

\`\`\`text
$ARGUMENTS
\`\`\`

If \`$ARGUMENTS\` is non-empty, use it as the starting feature description.

## Goal

Act as a **senior system architect and lead engineer**. Help the developer turn an idea into
one or more phased plan files in \`.speclet/plans/\` — **before** any code is written.

## How you must behave

- **Propose, do not decide.** For every meaningful decision (architecture, tech choices, phase
  boundaries, ordering, scope) present **2–4 concrete options** with honest trade-offs, recommend
  the one you'd pick as a lead engineer and say why — but the developer makes the final call.
- **Always ask, never assume.** When anything is unclear or could go more than one way, ask.
  Invite the developer's own ideas every time: "pick one of these, or tell me your own approach."
- **One question at a time** — wait for the answer before continuing.
- **Think like an architect** — surface risks, hidden complexity, dependencies, and sequencing
  concerns as suggestions to confirm, not as final rulings.

## Outline

1. **Load context**:
   - Read \`.speclet/context.md\` — stack, conventions, constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — respect its ground rules
   - If \`.speclet/architecture.md\` or existing \`.speclet/plans/\` files exist, read them so you extend rather than duplicate

2. **Interview** (one question at a time, each with options + a recommendation):
   - **Scope** — what are you building? Confirm what is in/out of scope.
   - **Architecture approach** — propose 2–4 candidate approaches with trade-offs; recommend one; ask them to choose or propose their own.
   - **Phase breakdown** — what does "done" look like? Suggest 3–8 phases, each with a name and 2–4 sentence deliverables. Ask them to confirm/adjust/split/merge. Do NOT generate tasks here.
   - **Dependencies & ordering** — recommend a build order; flag optional/deferrable phases; confirm.
   - **File structure** — recommend where new code lives and which modules change; confirm.

3. **Write the plan** once decisions are confirmed:
   \`\`\`markdown
   # <Feature Name>

   > Plan created interactively via /speclet.plan.

   ## Phase 1: <Name>
   <2–4 sentence description>

   ## Phase 2: <Name>
   <Description>
   \`\`\`
   - File naming: \`01-<feature-slug>.md\` or numbered \`01-backend.md\`, \`02-frontend.md\` — lowercase, hyphens.
   - Each phase = one \`##\` heading. Keep descriptions high-level — tasks come later.

4. **Report**: List the files created, confirm the phase count, and suggest the "Generate Tasks" handoff.
`;
}

function specletMapAgent(): string {
  return `---
description: Perform a full retroactive speclet setup of an existing codebase — scan, document, infer ground rules, and record all past work as completed tasks.
handoffs:
  - label: Set Ground Rules
    agent: speclet.constitution
    prompt: Review and refine the constitution that was inferred from the codebase
    send: true
  - label: Plan New Features
    agent: speclet.tasks
    prompt: Generate tasks for the new feature phases
    send: true
---

## Goal

Produce every speclet file as if this project had been using speclet from the start, with all existing
work already documented and marked done — so new features can be planned and implemented immediately.

## Files to produce

| File | What it is |
|---|---|
| \`.speclet/context.md\` | Real stack, module structure, conventions, constraints |
| \`.speclet/architecture.md\` | Module map, key files, data flow, integrations, tech debt |
| \`.speclet/constitution.md\` | Ground rules inferred from the codebase |
| \`.speclet/plans/01-existing.md\` | Plan file with phases describing what was built |
| \`.speclet/tasks/index.md\` | Phase map |
| \`.speclet/tasks/phase-N-*.md\` | Task files — all tasks marked \`[x]\` done |

## Instructions

1. **Deep scan the codebase**:
   - Read project tree and all config files (package.json, tsconfig, lint/prettier configs, CI, Dockerfile)
   - Read 2–4 representative source files per layer/module
   - Read README, CHANGELOG, docs/, ADR files
   - Check \`git log --oneline -20\` if available

2. **Write \`.speclet/context.md\`** — real stack, module structure, conventions, test setup, constraints

3. **Write \`.speclet/architecture.md\`** — module table, key files, data flow, external integrations, tech debt

4. **Write \`.speclet/constitution.md\`** — infer from evidence, do NOT ask questions:
   - Code Quality: from lint/prettier configs, tsconfig strict settings
   - Architecture Principles: from folder structure, import patterns, layering
   - Testing Requirements: from test config, coverage settings, sample test files
   - What To Avoid: from lint rules that ban things, absent patterns
   - Definition of Done: from CI pipeline, PR templates
   - Remove the \`<!-- speclet:unfilled -->\` marker — this constitution is filled

5. **Group existing work into phases** — divide all implemented work into logical increments in the order they would have been built

6. **Write \`.speclet/plans/01-existing.md\`** — one \`##\` heading per phase with a 2–4 sentence description

7. **Write \`.speclet/tasks/index.md\`** — one bullet per phase pointing at its task file

8. **Write task files** — one \`.speclet/tasks/phase-N-<slug>.md\` per phase:
   - Header: \`Status: Complete\` and \`Completed: <date>\`
   - 5–10 concrete tasks per phase, every task \`[x]\` done

9. **Report**: list all files written, stack detected, phases mapped, suggest next steps
`;
}

function specletConstitutionAgent(): string {
  return `---
description: Fill in or update the speclet project constitution with your project's ground rules and principles.
handoffs:
  - label: Generate Tasks
    agent: speclet.tasks
    prompt: Generate tasks for all phases
    send: true
---

## User Input

\`\`\`text
$ARGUMENTS
\`\`\`

You **MUST** consider the user input before proceeding (if not empty).

## Goal

Fill in or update \`.speclet/constitution.md\` with concrete project ground rules.
The constitution is injected into every future speclet prompt, so keep it concise and actionable.

## Outline

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and conventions
   - Read \`.speclet/constitution.md\` — current state (may contain placeholder markers)

2. **Check constitution state**:
   - If the file contains \`<!-- speclet:unfilled -->\`, this is a **first-time setup**
   - Otherwise, this is an **update or review**

3. **First-time setup** (if unfilled):
   Ask the developer the following questions **one section at a time**. Wait for answers before proceeding.

   **Code Quality**
   - What coding standards or style guides should be followed?
   - Are there linting or formatting tools to enforce (ESLint, Prettier, etc.)?

   **Architecture Principles**
   - What architectural patterns should be used (e.g. layered, hexagonal, feature-based)?
   - Are there any patterns to explicitly avoid?

   **Testing Requirements**
   - What level of test coverage is expected?
   - Which types of tests are required (unit, integration, e2e)?
   - What testing libraries should be used?

   **What To Avoid**
   - Libraries, patterns, or approaches that are off-limits?
   - Any security or compliance rules to follow?

   **Definition of Done**
   - What does "done" mean for a task in this project?
   - Is there a review or approval process?

4. **Update mode** (if already filled):
   - If \`$ARGUMENTS\` specifies a section to update, focus on that section
   - Otherwise review the full constitution and ask if anything needs updating

5. **Write back**: Rewrite \`.speclet/constitution.md\` with answers filled in.
   - Remove the \`<!-- speclet:unfilled -->\` marker line
   - Keep the file concise — it is injected into every future prompt

6. **Report**: Confirm the file was saved and list which sections were updated.
`;
}

function specletTasksAgent(): string {
  return `---
description: Generate concrete, ordered tasks for one or all plan phases and write them to the task files.
handoffs:
  - label: Analyze for Consistency
    agent: speclet.analyze
    prompt: Run a consistency analysis across all phases
    send: true
  - label: Start Implementation
    agent: speclet.implement
    prompt: Start implementing the first phase
    send: true
---

## User Input

\`\`\`text
$ARGUMENTS
\`\`\`

You **MUST** consider the user input before proceeding (if not empty).
If a phase number or name is provided in \`$ARGUMENTS\`, process **only that phase**.
Otherwise process all phases one at a time.

## Goal

Break plan phases into concrete, actionable development tasks and write them to the task files listed in \`.speclet/tasks/index.md\`.

## Outline

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack, conventions, and constraints
   - Read \`.speclet/tasks/index.md\` — the phase map (lists all phases and their task file paths)
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it for project ground rules

2. **Determine scope**:
   - If \`$ARGUMENTS\` contains a phase number or name, process only that phase
   - Otherwise process all phases, **one at a time** — never load all phase files simultaneously

3. **For each phase to process**:
   - Find the phase entry in \`.speclet/tasks/index.md\`
   - If the task file already exists (e.g., \`.speclet/tasks/phase-1-setup.md\`), read it — you may revise existing tasks
   - If the task file does not exist, find the source plan file from \`.speclet/plans/\` listed for that phase
   - Generate concrete, ordered tasks for the phase
   - Write the tasks to the task file path listed in the index

4. **Task format rules**:
   \`\`\`
   - [ ] **Task title** — brief description of what to do and what done looks like
   \`\`\`
   - Each task must be **atomic** — one clear unit of work
   - Each task must be **specific** — enough detail to implement without re-reading the plan
   - Tasks must be **ordered** — listed in the sequence they should be done
   - Do not duplicate tasks across phases
   - Reference the stack from \`.speclet/context.md\`
   - Respect constraints from \`.speclet/constitution.md\` (testing, architecture, quality rules)

5. **Report**: List the task files created or updated and the total task count per phase.
`;
}

function specletImplementAgent(): string {
  return `---
description: Implement all tasks in a single phase, marking each task done as you go.
handoffs:
  - label: Implement Next Phase
    agent: speclet.implement
    prompt: Implement the next phase
  - label: Review Learned Rules
    agent: speclet.learn
    prompt: Review and merge the rules captured during implementation
---

## User Input

\`\`\`text
$ARGUMENTS
\`\`\`

You **MUST** consider the user input before proceeding (if not empty).
\`$ARGUMENTS\` should contain the phase number or name to implement (e.g., \`1\` or \`Phase 2\`).

## Goal

Work through every unchecked task in a single phase file, implementing each one in order and marking it \`[x]\` when complete.

## Outline

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack, conventions, and constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — honour all quality rules, architecture principles, and Definition of Done
   - If \`.speclet/constitution.learned.md\` exists, read it — follow any rules in the \`## Pending Rules\` section
   - Read \`.speclet/tasks/index.md\` — the phase map

2. **Resolve the phase**:
   - Use \`$ARGUMENTS\` to identify the phase by number or name
   - If \`$ARGUMENTS\` is empty, ask the user which phase to implement and list available phases from the index
   - Find the task file path from the index (e.g., \`.speclet/tasks/phase-1-setup.md\`)
   - If the task file does not exist, stop and suggest running \`/speclet.tasks\` first

3. **Load the phase file**:
   - Read **ONLY** the requested phase task file — do not load any other phase files
   - Count and list the unchecked tasks (\`- [ ]\`)

4. **Implement tasks in order**:
   - Work through each unchecked task \`- [ ]\` sequentially
   - Implement the task following the stack in \`.speclet/context.md\` exactly
   - If a task is ambiguous, add a brief inline code comment and note the ambiguity — do not guess
   - Mark each task done immediately after completing it: change \`- [ ]\` to \`- [x]\`
   - Report progress after each task

5. **On completion**:
   - Verify all tasks in the phase are marked \`[x]\`
   - Update the phase file header with:
     \`\`\`
     Status: Complete
     Completed: <today's date>
     \`\`\`
   - Summarize what was built: files created, endpoints added, key decisions made
   - If any rules were appended to \`.speclet/constitution.learned.md\`, mention them and offer the "Review Learned Rules" handoff

## Rules

- Follow the stack and conventions in \`.speclet/context.md\` exactly
- Honour all rules from \`.speclet/constitution.md\` (quality, architecture, DoD)
- Do **NOT** load or modify other phase files
- Halt and ask for guidance if a non-ambiguous blocker is encountered

## Capturing Learned Rules

If you correct a bash command, discover a project pattern, or notice something that should always be done:
→ Append it to \`.speclet/constitution.learned.md\` under \`## Pending Rules\`:

\`\`\`
### [YYYY-MM-DD] category: short-title
**Rule:** What to always do.
**Why:** What went wrong or why this matters.
\`\`\`

Categories: \`bash\`, \`pattern\`, \`architecture\`, \`testing\`, \`tooling\`
`;
}

function specletLearnAgent(): string {
  return `---
description: Review auto-captured rules from implementation sessions and merge them into the project constitution.
handoffs:
  - label: Start Implementation
    agent: speclet.implement
    prompt: Continue implementing
    send: true
---

## Goal

Review pending rules in \`.speclet/constitution.learned.md\` and decide which ones to permanently add to \`.speclet/constitution.md\`.

## Outline

1. **Check for pending rules**:
   - Read \`.speclet/constitution.learned.md\`
   - If no \`### \` entries exist under \`## Pending Rules\`, report "No pending rules" and stop

2. **Load current constitution**:
   - Read \`.speclet/constitution.md\`

3. **Review rules one at a time**:
   - Present each pending rule to the developer
   - Ask: **Keep (merge into constitution), Skip (discard), or Defer (leave for later)?**
   - Wait for the answer before showing the next rule

4. **Apply decisions**:
   - **Keep**: Add the rule to the appropriate section of \`.speclet/constitution.md\`. Create a new section if needed.
   - **Skip**: Remove the rule entry from \`.speclet/constitution.learned.md\`.
   - **Defer**: Leave the rule unchanged in \`.speclet/constitution.learned.md\`.

5. **Write files**:
   - Rewrite \`.speclet/constitution.md\` with all kept rules merged in
   - Rewrite \`.speclet/constitution.learned.md\` with only deferred rules remaining
     (if none remain, keep the file with its header and empty \`## Pending Rules\` section)

6. **Report**: Confirm how many rules were merged, skipped, and deferred.
`;
}

function specletClarifyAgent(): string {
  return `---
description: Generate targeted clarifying questions about the plan or a specific phase before implementation begins.
handoffs:
  - label: Generate Tasks
    agent: speclet.tasks
    prompt: Generate tasks for all phases
    send: true
---

## User Input

\`\`\`text
$ARGUMENTS
\`\`\`

You **MUST** consider the user input before proceeding (if not empty).
If a phase number or name is provided in \`$ARGUMENTS\`, clarify **only that phase**.
Otherwise clarify the full plan.

## Goal

Detect and surface ambiguities, missing decisions, and underspecified areas in the plan **before** task generation or implementation begins.

## Outline

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it too

2. **Load the plan or phase**:
   - If \`$ARGUMENTS\` specifies a phase, find its task file in \`.speclet/tasks/index.md\` and read it
   - If no phase specified, read the plan files in \`.speclet/plans/\`

3. **Scan for ambiguities** across these categories:
   - **Scope** — what is explicitly in/out of scope?
   - **Technical** — ambiguous implementation decisions (libraries, patterns, data shapes)
   - **Dependencies** — external services, APIs, or data sources not fully specified
   - **Edge cases** — scenarios not addressed (errors, empty states, concurrency, limits)
   - **Non-functional** — performance, security, or scalability requirements missing measurable targets

4. **Generate clarifying questions**:
   - Maximum **5 questions** total, prioritized by impact on implementation
   - Each question must be answerable with a short answer or a choice between 2–4 options
   - For each question with options, **recommend the best option** with brief reasoning
   - Ask questions **one at a time** — wait for the answer before the next

5. **Record answers** (if user answers during this session):
   - After each answer, note whether it changes implementation approach
   - If the plan or task file should be updated based on the answer, do so immediately

6. **Report**:
   - Number of questions asked
   - Summary of any decisions made
   - Suggested next step (\`/speclet.tasks\` or \`/speclet.implement\`)
`;
}

function specletAnalyzeAgent(): string {
  return `---
description: Analyze speclet tasks for gaps, conflicts, and risks, then update task files and implement fixes.
handoffs:
  - label: Start Implementation
    agent: speclet.implement
    prompt: Start implementing the first phase
    send: true
---

## User Input

\`\`\`text
$ARGUMENTS
\`\`\`

You **MUST** consider the user input before proceeding (if not empty).
If a phase number or name is provided in \`$ARGUMENTS\`, analyze **only that phase**.
Otherwise analyze all phases.
If the user provided a follow-up instruction (e.g., "fix the found issues"), **run the full analysis first**, then address that instruction.

## Goal

Identify inconsistencies, gaps, conflicts, and risks across task files **before implementation begins**, then handle any follow-up instruction the user provided.

**MUST RUN THE ANALYSIS FIRST** — do not skip to the follow-up instruction. Output the analysis report, then address the follow-up.

## Outline

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and constraints
   - Read \`.speclet/tasks/index.md\` — full phase map
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — constitution violations are always **CRITICAL**

2. **Load task files**:
   - If \`$ARGUMENTS\` specifies a phase, load only that phase file
   - Otherwise load each phase file **one at a time** — never all at once
   - For each phase file, extract: task IDs, descriptions, file paths

3. **Run detection passes**:

   **A. Conflicts** — tasks that contradict or overlap each other
   - Same file being created by two tasks in different phases
   - Contradictory patterns (e.g., one task uses REST, another uses GraphQL without explanation)

   **B. Gaps** — missing tasks implied by the plan
   - Features mentioned in \`.speclet/plans/\` with no corresponding tasks
   - Dependencies between tasks that aren't captured (e.g., a service used before it's created)

   **C. Risks** — tasks that are vague, high-effort, or have unclear success criteria
   - Tasks without file paths
   - Tasks described as "implement the whole X" without breakdown
   - Tasks that seem to span multiple phases

   **D. Constitution violations** (if constitution is present)
   - Any task that contradicts a principle in \`.speclet/constitution.md\`
   - These are always **CRITICAL** severity

4. **Produce analysis report** (markdown):

   \`\`\`
   ## Analysis Report

   ### Conflicts
   - [ ] **[phase-file]** Description of conflict

   ### Gaps
   - [ ] **[phase-file]** Description of gap

   ### Risks
   - [ ] **[phase-file]** Description of risk

   ### Constitution Violations
   - [ ] **[phase-file]** Description of violation (CRITICAL)

   ### Suggestions
   - [ ] Optional improvements to task ordering or grouping
   \`\`\`
   If no issues found in a category, write "None found."

5. **Provide next actions**:
   - If CRITICAL issues exist: recommend resolving before \`/speclet-implement\`
   - If only LOW/MEDIUM: user may proceed, provide improvement suggestions
   - Suggest explicit next command

## Follow-up Handling

If the user provided a follow-up instruction (e.g., "fix the found issues"):

1. **Update task/phase files FIRST** — add, modify, or remove tasks in the affected phase files to reflect the needed changes. Create new phase/task files if needed. This keeps task files in sync as the source of truth.
2. **Then implement code changes** — make the actual code edits described by the updated tasks.
Task files MUST be updated before code changes — never skip straight to implementation.
`;
}

function cursorRules(): string {
  return `---
description: speclet spec-driven workflow rules
globs: .speclet/**
alwaysApply: false
---

# Speclet Workflow Rules

When working on any speclet-related task:

1. Always read \`.speclet/context.md\` first — it defines the project stack and conventions
2. If \`.speclet/constitution.md\` exists and is filled in (no \`<!-- speclet:unfilled -->\` marker), read it too — it sets project ground rules that must be followed
3. Use \`.speclet/tasks/index.md\` as the phase map — never guess phase file names
4. Load one phase file at a time from \`.speclet/tasks/\` — never all at once
5. If \`.speclet/architecture.md\` exists, read it when implementing features that touch existing modules
6. Follow the matching prompt in \`.speclet/prompts/\` for each command type:
   - Plan: \`.speclet/prompts/plan.md\`
   - Map: \`.speclet/prompts/map.md\`
   - Constitution: \`.speclet/prompts/constitution.md\`
   - Clarify: \`.speclet/prompts/clarify.md\`
   - Analyze: \`.speclet/prompts/analyze.md\`
   - Tasks: \`.speclet/prompts/tasks.md\`
   - Implement: \`.speclet/prompts/implement.md\`

## Map (existing projects)
When mapping an existing codebase, explore the project structure, read config and source files,
then write \`.speclet/context.md\` (stack, conventions) and \`.speclet/architecture.md\` (module map).

## Implement
When implementing a phase, work through each \`- [ ]\` task in order, marking each \`- [x]\` when done.
Do not load other phase files while implementing one phase.
If \`.speclet/architecture.md\` exists, use it to understand existing module boundaries before making changes.

## Tasks
When generating tasks, write them to the phase file listed in \`.speclet/tasks/index.md\`.
One phase at a time to minimise token usage.
`;
}

// ─── Vibe skill templates ──────────────────────────────────────────────────────

function vibeAgentsMd(): string {  return `<!-- SPECLET START -->
## speclet — Spec-driven development

This project uses speclet for spec-driven development.

Key speclet files:
- Project context: \`.speclet/context.md\` — read this first on every speclet task
- Ground rules: \`.speclet/constitution.md\` — read if present and filled in (no \`<!-- speclet:unfilled -->\` marker)
- Architecture map: \`.speclet/architecture.md\` — read when implementing features that touch existing modules (if present)
- Plan files: \`.speclet/plans/\` — original feature plans
- Task index: \`.speclet/tasks/index.md\` — the phase map, always use this to find phase files
- Phase tasks: \`.speclet/tasks/phase-N-*.md\` — one file per phase, load only what you need

Use the \`/speclet-plan\`, \`/speclet-constitution\`, \`/speclet-tasks\`, \`/speclet-implement\`, \`/speclet-clarify\`, and \`/speclet-analyze\` slash commands to run the speclet workflow.
<!-- SPECLET END -->
`;
}

function vibeSkillFrontmatter(
  name: string,
  description: string,
  tools: string[]
): string {
  const toolList = tools.map((t) => `  - ${t}`).join("\n");
  return `---
name: ${name}
description: ${description}
user-invocable: true
allowed-tools:
${toolList}
---
`;
}

function vibeSkillPlan(): string {
  return (
    vibeSkillFrontmatter(
      "speclet-plan",
      "Act as a senior system architect / lead engineer and help the developer turn an idea into a phased plan — proposing options with trade-offs and letting the developer decide.",
      ["read", "write_file", "ask_user_question"]
    ) +
    `
# speclet plan

Act as a **senior system architect and lead engineer**. Help the developer turn an idea into one or more phased plan files in \`.speclet/plans/\` — **before** any code is written.

## How you must behave

- **Propose, do not decide.** For every meaningful decision (architecture, tech choices, phase boundaries, ordering, scope) present **2–4 concrete options** with trade-offs, recommend the one you'd pick as a lead engineer and say why — but the developer makes the final call.
- **Always ask, never assume.** When anything is unclear or could go more than one way, ask. Invite the developer's own ideas: "pick one of these, or tell me your own approach."
- **One question at a time** — wait for the answer before continuing.

## Instructions

If a topic was provided in the user's message, use it as the starting feature description.

1. **Load context**:
   - Read \`.speclet/context.md\` — stack, conventions, constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — respect its ground rules
   - If \`.speclet/architecture.md\` or existing \`.speclet/plans/\` files exist, read them so you extend rather than duplicate

2. **Interview** (one question at a time, each with options + a recommendation):
   - **Scope** — what are you building? Confirm what is in/out of scope.
   - **Architecture approach** — propose 2–4 candidate approaches with trade-offs; recommend one; ask them to choose or propose their own.
   - **Phase breakdown** — what does "done" look like? Suggest 3–8 phases, each with a name and 2–4 sentence deliverables. Ask them to confirm/adjust/split/merge. Do NOT generate tasks here.
   - **Dependencies & ordering** — recommend a build order; flag optional/deferrable phases; confirm.
   - **File structure** — recommend where new code lives and which modules change; confirm.

3. **Write the plan** once decisions are confirmed:
   \`\`\`markdown
   # <Feature Name>

   > Plan created interactively via /speclet-plan.

   ## Phase 1: <Name>
   <2–4 sentence description>

   ## Phase 2: <Name>
   <Description>
   \`\`\`
   - File naming: \`01-<feature-slug>.md\` or numbered \`01-backend.md\`, \`02-frontend.md\` — lowercase, hyphens.
   - Each phase = one \`##\` heading. Keep descriptions high-level — tasks come later.

4. **Report**: List the files created, confirm the phase count, and suggest \`/speclet-tasks\` as the next step.
`
  );
}

function vibeSkillMap(): string {
  return (
    vibeSkillFrontmatter(
      "speclet-map",
      "Perform a full retroactive speclet setup of an existing codebase — scan, document, infer ground rules, and record all past work as completed tasks.",
      ["read", "write_file", "grep", "bash"]
    ) +
    `
# speclet map

Produce every speclet file as if this project had been using speclet from the start, with all existing work already documented and marked done — so new features can be planned and implemented immediately.

## Files to produce

| File | What it is |
|---|---|
| \`.speclet/context.md\` | Real stack, module structure, conventions, constraints |
| \`.speclet/architecture.md\` | Module map, key files, data flow, integrations, tech debt |
| \`.speclet/constitution.md\` | Ground rules inferred from the codebase |
| \`.speclet/plans/01-existing.md\` | Plan file with phases describing what was built |
| \`.speclet/tasks/index.md\` | Phase map |
| \`.speclet/tasks/phase-N-*.md\` | Task files — all tasks marked \`[x]\` done |

## Instructions

1. **Deep scan the codebase**:
   - Read project tree and all config files (package.json, tsconfig, lint/prettier configs, CI, Dockerfile)
   - Read 2–4 representative source files per layer/module
   - Read README, CHANGELOG, docs/, ADR files
   - Check \`git log --oneline -20\` if available

2. **Write \`.speclet/context.md\`** — real stack, module structure, conventions, test setup, constraints

3. **Write \`.speclet/architecture.md\`** — module table, key files, data flow, external integrations, tech debt

4. **Write \`.speclet/constitution.md\`** — infer from evidence, do NOT ask questions:
   - Code Quality: from lint/prettier configs, tsconfig strict settings
   - Architecture Principles: from folder structure, import patterns, layering
   - Testing Requirements: from test config, coverage settings, sample test files
   - What To Avoid: from lint rules that ban things, absent patterns
   - Definition of Done: from CI pipeline, PR templates
   - Remove the \`<!-- speclet:unfilled -->\` marker — this constitution is filled

5. **Group existing work into phases** — divide all implemented work into logical increments in the order they would have been built

6. **Write \`.speclet/plans/01-existing.md\`** — one \`##\` heading per phase with a 2–4 sentence description

7. **Write \`.speclet/tasks/index.md\`** — one bullet per phase pointing at its task file

8. **Write task files** — one \`.speclet/tasks/phase-N-<slug>.md\` per phase:
   - Header: \`Status: Complete\` and \`Completed: <date>\`
   - 5–10 concrete tasks per phase, every task \`[x]\` done

9. **Report**: list all files written, stack detected, phases mapped, suggest next steps
`
  );
}

function vibeSkillConstitution(): string {  return (
    vibeSkillFrontmatter(
      "speclet-constitution",
      "Fill in or update the speclet project constitution with your project's ground rules and principles.",
      ["read", "write_file", "ask_user_question"]
    ) +
    `
# speclet constitution

Fill in or update \`.speclet/constitution.md\` with concrete project ground rules.

## Instructions

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and conventions
   - Read \`.speclet/constitution.md\` — current state (may contain placeholder markers)

2. **Check constitution state**:
   - If the file contains \`<!-- speclet:unfilled -->\`, this is a **first-time setup**
   - Otherwise, this is an **update or review**

3. **First-time setup** (if unfilled):
   Ask the developer the following questions **one section at a time**. Wait for answers before proceeding.

   **Code Quality**
   - What coding standards or style guides should be followed?
   - Are there linting or formatting tools to enforce (ESLint, Prettier, etc.)?

   **Architecture Principles**
   - What architectural patterns should be used (e.g. layered, hexagonal, feature-based)?
   - Are there any patterns to explicitly avoid?

   **Testing Requirements**
   - What level of test coverage is expected?
   - Which types of tests are required (unit, integration, e2e)?
   - What testing libraries should be used?

   **What To Avoid**
   - Libraries, patterns, or approaches that are off-limits?
   - Any security or compliance rules to follow?

   **Definition of Done**
   - What does "done" mean for a task in this project?
   - Is there a review or approval process?

4. **Update mode** (if already filled):
   - If \`$ARGUMENTS\` specifies a section to update, focus on that section
   - Otherwise review the full constitution and ask if anything needs updating

5. **Write back**: Rewrite \`.speclet/constitution.md\` with answers filled in.
   - Remove the \`<!-- speclet:unfilled -->\` marker line
   - Keep the file concise — it is injected into every future prompt

6. **Report**: Confirm the file was saved and list which sections were updated.
`
  );
}

function vibeSkillClarify(): string {
  return (
    vibeSkillFrontmatter(
      "speclet-clarify",
      "Generate targeted clarifying questions about the plan or a specific phase before implementation begins.",
      ["read", "write_file", "ask_user_question"]
    ) +
    `
# speclet clarify

Detect and surface ambiguities, missing decisions, and underspecified areas in the plan **before** task generation or implementation begins.

## Instructions

If a phase number or name is provided in the user's message, clarify **only that phase**. Otherwise clarify the full plan.

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it too

2. **Load the plan or phase**:
   - If a phase was specified, find its task file in \`.speclet/tasks/index.md\` and read it
   - If no phase specified, read the plan files in \`.speclet/plans/\`

3. **Scan for ambiguities** across these categories:
   - **Scope** — what is explicitly in/out of scope?
   - **Technical** — ambiguous implementation decisions (libraries, patterns, data shapes)
   - **Dependencies** — external services, APIs, or data sources not fully specified
   - **Edge cases** — scenarios not addressed (errors, empty states, concurrency, limits)
   - **Non-functional** — performance, security, or scalability requirements missing measurable targets

4. **Generate clarifying questions**:
   - Maximum **5 questions** total, prioritized by impact on implementation
   - Each question must be answerable with a short answer or a choice between 2–4 options
   - For each question with options, **recommend the best option** with brief reasoning
   - Ask questions **one at a time** — wait for the answer before the next

5. **Record answers** (if user answers during this session):
   - After each answer, note whether it changes implementation approach
   - If the plan or task file should be updated based on the answer, do so immediately

6. **Report**:
   - Number of questions asked
   - Summary of any decisions made
   - Suggested next step (\`/speclet-tasks\` or \`/speclet-implement\`)
`
  );
}

function vibeSkillAnalyze(): string {
  return (
    vibeSkillFrontmatter(
      "speclet-analyze",
      "Analyze speclet tasks for gaps, conflicts, risks, and constitution violations, then update task files and implement fixes.",
      ["read", "grep", "write_file", "edit", "bash"]
    ) +
    `
# speclet analyze

Identify inconsistencies, gaps, conflicts, and risks across task files **before implementation begins**, then handle any follow-up instruction.

**MUST RUN THE ANALYSIS FIRST** — do not skip to the follow-up. Output the analysis report, then address what the user asked.

## Instructions

If a phase number or name is provided in the user's message, analyze **only that phase**. Otherwise analyze all phases.
If the user provided a follow-up instruction (e.g., "fix the found issues"), run the full analysis first, then address that instruction.

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and constraints
   - Read \`.speclet/tasks/index.md\` — full phase map
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — constitution violations are always **CRITICAL**

2. **Load task files**:
   - If a phase was specified, load only that phase file
   - Otherwise load each phase file **one at a time** — never all at once
   - For each phase file, extract: task IDs, descriptions, file paths

3. **Run detection passes**:

   **A. Conflicts** — tasks that contradict or overlap each other
   - Same file being created by two tasks in different phases
   - Contradictory patterns (e.g., one task uses REST, another uses GraphQL without explanation)

   **B. Gaps** — missing tasks implied by the plan
   - Features mentioned in \`.speclet/plans/\` with no corresponding tasks
   - Dependencies between tasks that aren't captured (e.g., a service used before it's created)

   **C. Risks** — tasks that are vague, high-effort, or have unclear success criteria
   - Tasks without file paths
   - Tasks described as "implement the whole X" without breakdown
   - Tasks that seem to span multiple phases

   **D. Constitution violations** (if constitution is present)
   - Any task that contradicts a principle in \`.speclet/constitution.md\`
   - These are always **CRITICAL** severity

4. **Produce analysis report** (markdown):

   \`\`\`
   ## Analysis Report

   ### Conflicts
   - [ ] **[phase-file]** Description of conflict

   ### Gaps
   - [ ] **[phase-file]** Description of gap

   ### Risks
   - [ ] **[phase-file]** Description of risk

   ### Constitution Violations
   - [ ] **[phase-file]** Description of violation (CRITICAL)

   ### Suggestions
   - [ ] Optional improvements to task ordering or grouping
   \`\`\`
   If no issues found in a category, write "None found."

5. **Provide next actions**:
   - If CRITICAL issues exist: recommend resolving before \`/speclet-implement\`
   - If only LOW/MEDIUM: user may proceed, provide improvement suggestions
   - Suggest explicit next command

## Follow-up Handling

If the user provided a follow-up instruction (e.g., "fix the found issues"):

1. **Update task/phase files FIRST** — add, modify, or remove tasks in the affected phase files to reflect the needed changes. Create new phase/task files if needed. This keeps task files in sync as the source of truth.
2. **Then implement code changes** — make the actual code edits described by the updated tasks.
Task files MUST be updated before code changes — never skip straight to implementation.
`
  );
}

function vibeSkillTasks(): string {
  return (
    vibeSkillFrontmatter(
      "speclet-tasks",
      "Generate concrete, ordered tasks for one or all plan phases and write them to the task files.",
      ["read", "write_file", "grep"]
    ) +
    `
# speclet tasks

Break plan phases into concrete, actionable development tasks and write them to the task files listed in \`.speclet/tasks/index.md\`.

## Instructions

If a phase number or name is provided in the user's message, process **only that phase**. Otherwise process all phases one at a time.

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack, conventions, and constraints
   - Read \`.speclet/tasks/index.md\` — the phase map (lists all phases and their task file paths)
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it for project ground rules

2. **Determine scope**:
   - If a phase number or name was provided, process only that phase
   - Otherwise process all phases, **one at a time** — never load all phase files simultaneously

3. **For each phase to process**:
   - Find the phase entry in \`.speclet/tasks/index.md\`
   - If the task file already exists (e.g., \`.speclet/tasks/phase-1-setup.md\`), read it — you may revise existing tasks
   - If the task file does not exist, find the source plan file from \`.speclet/plans/\` listed for that phase
   - Generate concrete, ordered tasks for the phase
   - Write the tasks to the task file path listed in the index

4. **Task format rules**:
   \`\`\`
   - [ ] **Task title** — brief description of what to do and what done looks like
   \`\`\`
   - Each task must be **atomic** — one clear unit of work
   - Each task must be **specific** — enough detail to implement without re-reading the plan
   - Tasks must be **ordered** — listed in the sequence they should be done
   - Do not duplicate tasks across phases
   - Reference the stack from \`.speclet/context.md\`
   - Respect constraints from \`.speclet/constitution.md\` (testing, architecture, quality rules)

5. **Report**: List the task files created or updated and the total task count per phase.
`
  );
}

function vibeSkillImplement(): string {
  return (
    vibeSkillFrontmatter(
      "speclet-implement",
      "Implement all tasks in a single phase, marking each task done as you go.",
      ["read", "write_file", "edit", "bash", "grep", "ask_user_question"]
    ) +
    `
# speclet implement

Work through every unchecked task in a single phase file, implementing each one in order and marking it \`[x]\` when complete.

## Instructions

The phase number or name to implement must be provided in the user's message (e.g., \`1\` or \`Phase 2\`).

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack, conventions, and constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — honour all quality rules, architecture principles, and Definition of Done
   - If \`.speclet/constitution.learned.md\` exists, read it — follow any rules in the \`## Pending Rules\` section
   - Read \`.speclet/tasks/index.md\` — the phase map

2. **Resolve the phase**:
   - Use the phase number or name from the user's message to identify the phase
   - If no phase was specified, ask the user which phase to implement and list available phases from the index
   - Find the task file path from the index (e.g., \`.speclet/tasks/phase-1-setup.md\`)
   - If the task file does not exist, stop and suggest running \`/speclet-tasks\` first

3. **Load the phase file**:
   - Read **ONLY** the requested phase task file — do not load any other phase files
   - Count and list the unchecked tasks (\`- [ ]\`)

4. **Implement tasks in order**:
   - Work through each unchecked task \`- [ ]\` sequentially
   - Implement the task following the stack in \`.speclet/context.md\` exactly
   - If a task is ambiguous, add a brief inline code comment and note the ambiguity — do not guess
   - Mark each task done immediately after completing it: change \`- [ ]\` to \`- [x]\`
   - Report progress after each task

5. **On completion**:
   - Verify all tasks in the phase are marked \`[x]\`
   - Update the phase file header with:
     \`\`\`
     Status: Complete
     Completed: <today's date>
     \`\`\`
   - Summarize what was built: files created, endpoints added, key decisions made
   - If any rules were appended to \`.speclet/constitution.learned.md\`, mention them and suggest running \`/speclet-learn\`

## Rules

- Follow the stack and conventions in \`.speclet/context.md\` exactly
- Honour all rules from \`.speclet/constitution.md\` (quality, architecture, DoD)
- Do **NOT** load or modify other phase files
- Halt and ask for guidance if a non-ambiguous blocker is encountered

## Capturing Learned Rules

If you correct a bash command, discover a project pattern, or notice something that should always be done:
→ Append it to \`.speclet/constitution.learned.md\` under \`## Pending Rules\`:

\`\`\`
### [YYYY-MM-DD] category: short-title
**Rule:** What to always do.
**Why:** What went wrong or why this matters.
\`\`\`

Categories: \`bash\`, \`pattern\`, \`architecture\`, \`testing\`, \`tooling\`
`
  );
}

function vibeSkillLearn(): string {
  return (
    vibeSkillFrontmatter(
      "speclet-learn",
      "Review auto-captured rules from implementation sessions and merge them into the constitution.",
      ["read", "write_file", "ask_user_question"]
    ) +
    `
# speclet learn

Review pending rules captured during implementation and decide which ones to permanently add to the project constitution.

## Instructions

1. **Check for pending rules**:
   - Read \`.speclet/constitution.learned.md\`
   - If no \`### \` entries exist under \`## Pending Rules\`, report "No pending rules" and stop

2. **Load current constitution**:
   - Read \`.speclet/constitution.md\`

3. **Review rules one at a time**:
   - Present each pending rule to the developer
   - Ask: **Keep (merge into constitution), Skip (discard), or Defer (leave for later)?**
   - Wait for the answer before showing the next rule

4. **Apply decisions**:
   - **Keep**: Add the rule to the appropriate section of \`.speclet/constitution.md\`. Create a new section if needed.
   - **Skip**: Remove the rule entry from \`.speclet/constitution.learned.md\`.
   - **Defer**: Leave the rule unchanged in \`.speclet/constitution.learned.md\`.

5. **Write files**:
   - Rewrite \`.speclet/constitution.md\` with all kept rules merged in
   - Rewrite \`.speclet/constitution.learned.md\` with only deferred rules remaining
     (if none remain, keep the file with its header and empty \`## Pending Rules\` section)

6. **Report**: Confirm how many rules were merged, skipped, and deferred.
`
  );
}

// ─── Command Code skill templates ────────────────────────────────────────────────

function ccSkillFrontmatter(
  name: string,
  description: string,
): string {
  return `---
name: ${name}
description: ${description}
---
`;
}

function ccSkillPlan(): string {
  return (
    ccSkillFrontmatter(
      "speclet-plan",
      "Act as a senior system architect / lead engineer and help the developer turn an idea into a phased plan — proposing options with trade-offs and letting the developer decide.",
    ) +
    `
# speclet plan

Act as a **senior system architect and lead engineer**. Help the developer turn an idea into one or more phased plan files in \`.speclet/plans/\` — **before** any code is written.

## How you must behave

- **Propose, do not decide.** For every meaningful decision (architecture, tech choices, phase boundaries, ordering, scope) present **2–4 concrete options** with trade-offs, recommend the one you'd pick as a lead engineer and say why — but the developer makes the final call.
- **Always ask, never assume.** When anything is unclear or could go more than one way, ask. Invite the developer's own ideas: "pick one of these, or tell me your own approach."
- **One question at a time** — wait for the answer before continuing.

## Instructions

If a topic was provided in the user's message, use it as the starting feature description.

1. **Load context**:
   - Read \`.speclet/context.md\` — stack, conventions, constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — respect its ground rules
   - If \`.speclet/architecture.md\` or existing \`.speclet/plans/\` files exist, read them so you extend rather than duplicate

2. **Interview** (one question at a time, each with options + a recommendation):
   - **Scope** — what are you building? Confirm what is in/out of scope.
   - **Architecture approach** — propose 2–4 candidate approaches with trade-offs; recommend one; ask them to choose or propose their own.
   - **Phase breakdown** — what does "done" look like? Suggest 3–8 phases, each with a name and 2–4 sentence deliverables. Ask them to confirm/adjust/split/merge. Do NOT generate tasks here.
   - **Dependencies & ordering** — recommend a build order; flag optional/deferrable phases; confirm.
   - **File structure** — recommend where new code lives and which modules change; confirm.

3. **Write the plan** once decisions are confirmed:
   \`\`\`markdown
   # <Feature Name>

   > Plan created interactively via /speclet-plan.

   ## Phase 1: <Name>
   <2–4 sentence description>

   ## Phase 2: <Name>
   <Description>
   \`\`\`
   - File naming: \`01-<feature-slug>.md\` or numbered \`01-backend.md\`, \`02-frontend.md\` — lowercase, hyphens.
   - Each phase = one \`##\` heading. Keep descriptions high-level — tasks come later.

4. **Report**: List the files created, confirm the phase count, and suggest \`/speclet-tasks\` as the next step.
`
  );
}

function ccSkillMap(): string {
  return (
    ccSkillFrontmatter(
      "speclet-map",
      "Perform a full retroactive speclet setup of an existing codebase — scan, document, infer ground rules, and record all past work as completed tasks.",
    ) +
    `
# speclet map

Produce every speclet file as if this project had been using speclet from the start, with all existing work already documented and marked done — so new features can be planned and implemented immediately.

## Files to produce

| File | What it is |
|---|---|
| \`.speclet/context.md\` | Real stack, module structure, conventions, constraints |
| \`.speclet/architecture.md\` | Module map, key files, data flow, integrations, tech debt |
| \`.speclet/constitution.md\` | Ground rules inferred from the codebase |
| \`.speclet/plans/01-existing.md\` | Plan file with phases describing what was built |
| \`.speclet/tasks/index.md\` | Phase map |
| \`.speclet/tasks/phase-N-*.md\` | Task files — all tasks marked \`[x]\` done |

## Instructions

1. **Deep scan the codebase**:
   - Read project tree and all config files (package.json, tsconfig, lint/prettier configs, CI, Dockerfile)
   - Read 2–4 representative source files per layer/module
   - Read README, CHANGELOG, docs/, ADR files
   - Check \`git log --oneline -20\` if available

2. **Write \`.speclet/context.md\`** — real stack, module structure, conventions, test setup, constraints

3. **Write \`.speclet/architecture.md\`** — module table, key files, data flow, external integrations, tech debt

4. **Write \`.speclet/constitution.md\`** — infer from evidence, do NOT ask questions:
   - Code Quality: from lint/prettier configs, tsconfig strict settings
   - Architecture Principles: from folder structure, import patterns, layering
   - Testing Requirements: from test config, coverage settings, sample test files
   - What To Avoid: from lint rules that ban things, absent patterns
   - Definition of Done: from CI pipeline, PR templates
   - Remove the \`<!-- speclet:unfilled -->\` marker — this constitution is filled

5. **Group existing work into phases** — divide all implemented work into logical increments in the order they would have been built

6. **Write \`.speclet/plans/01-existing.md\`** — one \`##\` heading per phase with a 2–4 sentence description

7. **Write \`.speclet/tasks/index.md\`** — one bullet per phase pointing at its task file

8. **Write task files** — one \`.speclet/tasks/phase-N-<slug>.md\` per phase:
   - Header: \`Status: Complete\` and \`Completed: <date>\`
   - 5–10 concrete tasks per phase, every task \`[x]\` done

9. **Report**: list all files written, stack detected, phases mapped, suggest next steps
`
  );
}

function ccSkillConstitution(): string {
  return (
    ccSkillFrontmatter(
      "speclet-constitution",
      "Fill in or update the speclet project constitution with your project's ground rules and principles.",
    ) +
    `
# speclet constitution

Fill in or update \`.speclet/constitution.md\` with concrete project ground rules.

## Instructions

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and conventions
   - Read \`.speclet/constitution.md\` — current state (may contain placeholder markers)

2. **Check constitution state**:
   - If the file contains \`<!-- speclet:unfilled -->\`, this is a **first-time setup**
   - Otherwise, this is an **update or review**

3. **First-time setup** (if unfilled):
   Ask the developer the following questions **one section at a time**. Wait for answers before proceeding.

   **Code Quality**
   - What coding standards or style guides should be followed?
   - Are there linting or formatting tools to enforce (ESLint, Prettier, etc.)?

   **Architecture Principles**
   - What architectural patterns should be used (e.g. layered, hexagonal, feature-based)?
   - Are there any patterns to explicitly avoid?

   **Testing Requirements**
   - What level of test coverage is expected?
   - Which types of tests are required (unit, integration, e2e)?
   - What testing libraries should be used?

   **What To Avoid**
   - Libraries, patterns, or approaches that are off-limits?
   - Any security or compliance rules to follow?

   **Definition of Done**
   - What does "done" mean for a task in this project?
   - Is there a review or approval process?

4. **Update mode** (if already filled):
   - If the user specifies a section to update, focus on that section
   - Otherwise review the full constitution and ask if anything needs updating

5. **Write back**: Rewrite \`.speclet/constitution.md\` with answers filled in.
   - Remove the \`<!-- speclet:unfilled -->\` marker line
   - Keep the file concise — it is injected into every future prompt

6. **Report**: Confirm the file was saved and list which sections were updated.
`
  );
}

function ccSkillClarify(): string {
  return (
    ccSkillFrontmatter(
      "speclet-clarify",
      "Generate targeted clarifying questions about the plan or a specific phase before implementation begins.",
    ) +
    `
# speclet clarify

Detect and surface ambiguities, missing decisions, and underspecified areas in the plan **before** task generation or implementation begins.

## Instructions

If a phase number or name is provided in the user's message, clarify **only that phase**. Otherwise clarify the full plan.

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it too

2. **Load the plan or phase**:
   - If a phase was specified, find its task file in \`.speclet/tasks/index.md\` and read it
   - If no phase specified, read the plan files in \`.speclet/plans/\`

3. **Scan for ambiguities** across these categories:
   - **Scope** — what is explicitly in/out of scope?
   - **Technical** — ambiguous implementation decisions (libraries, patterns, data shapes)
   - **Dependencies** — external services, APIs, or data sources not fully specified
   - **Edge cases** — scenarios not addressed (errors, empty states, concurrency, limits)
   - **Non-functional** — performance, security, or scalability requirements missing measurable targets

4. **Generate clarifying questions**:
   - Maximum **5 questions** total, prioritized by impact on implementation
   - Each question must be answerable with a short answer or a choice between 2–4 options
   - For each question with options, **recommend the best option** with brief reasoning
   - Ask questions **one at a time** — wait for the answer before the next

5. **Record answers** (if user answers during this session):
   - After each answer, note whether it changes implementation approach
   - If the plan or task file should be updated based on the answer, do so immediately

6. **Report**:
   - Number of questions asked
   - Summary of any decisions made
   - Suggested next step (\`/speclet-tasks\` or \`/speclet-implement\`)
`
  );
}

function ccSkillAnalyze(): string {
  return (
    ccSkillFrontmatter(
      "speclet-analyze",
      "Analyze speclet tasks for gaps, conflicts, risks, and constitution violations, then update task files and implement fixes.",
    ) +
    `
# speclet analyze

Identify inconsistencies, gaps, conflicts, and risks across task files **before implementation begins**, then handle any follow-up instruction.

**MUST RUN THE ANALYSIS FIRST** — do not skip to the follow-up. Output the analysis report, then address what the user asked.

## Instructions

If a phase number or name is provided in the user's message, analyze **only that phase**. Otherwise analyze all phases.
If the user provided a follow-up instruction (e.g., "fix the found issues"), run the full analysis first, then address that instruction.

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack and constraints
   - Read \`.speclet/tasks/index.md\` — full phase map
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — constitution violations are always **CRITICAL**

2. **Load task files**:
   - If a phase was specified, load only that phase file
   - Otherwise load each phase file **one at a time** — never all at once
   - For each phase file, extract: task IDs, descriptions, file paths

3. **Run detection passes**:

   **A. Conflicts** — tasks that contradict or overlap each other
   - Same file being created by two tasks in different phases
   - Contradictory patterns (e.g., one task uses REST, another uses GraphQL without explanation)

   **B. Gaps** — missing tasks implied by the plan
   - Features mentioned in \`.speclet/plans/\` with no corresponding tasks
   - Dependencies between tasks that aren't captured (e.g., a service used before it's created)

   **C. Risks** — tasks that are vague, high-effort, or have unclear success criteria
   - Tasks without file paths
   - Tasks described as "implement the whole X" without breakdown
   - Tasks that seem to span multiple phases

   **D. Constitution violations** (if constitution is present)
   - Any task that contradicts a principle in \`.speclet/constitution.md\`
   - These are always **CRITICAL** severity

4. **Produce analysis report** (markdown):

   \`\`\`
   ## Analysis Report

   ### Conflicts
   - [ ] **[phase-file]** Description of conflict

   ### Gaps
   - [ ] **[phase-file]** Description of gap

   ### Risks
   - [ ] **[phase-file]** Description of risk

   ### Constitution Violations
   - [ ] **[phase-file]** Description of violation (CRITICAL)

   ### Suggestions
   - [ ] Optional improvements to task ordering or grouping
   \`\`\`
   If no issues found in a category, write "None found."

5. **Provide next actions**:
   - If CRITICAL issues exist: recommend resolving before \`/speclet-implement\`
   - If only LOW/MEDIUM: user may proceed, provide improvement suggestions
   - Suggest explicit next command

## Follow-up Handling

If the user provided a follow-up instruction (e.g., "fix the found issues"):

1. **Update task/phase files FIRST** — add, modify, or remove tasks in the affected phase files to reflect the needed changes. Create new phase/task files if needed. This keeps task files in sync as the source of truth.
2. **Then implement code changes** — make the actual code edits described by the updated tasks.
Task files MUST be updated before code changes — never skip straight to implementation.
`
  );
}

function ccSkillTasks(): string {
  return (
    ccSkillFrontmatter(
      "speclet-tasks",
      "Generate concrete, ordered tasks for one or all plan phases and write them to the task files.",
    ) +
    `
# speclet tasks

Break plan phases into concrete, actionable development tasks and write them to the task files listed in \`.speclet/tasks/index.md\`.

## Instructions

If a phase number or name is provided in the user's message, process **only that phase**. Otherwise process all phases one at a time.

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack, conventions, and constraints
   - Read \`.speclet/tasks/index.md\` — the phase map (lists all phases and their task file paths)
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it for project ground rules

2. **Determine scope**:
   - If a phase number or name was provided, process only that phase
   - Otherwise process all phases, **one at a time** — never load all phase files simultaneously

3. **For each phase to process**:
   - Find the phase entry in \`.speclet/tasks/index.md\`
   - If the task file already exists (e.g., \`.speclet/tasks/phase-1-setup.md\`), read it — you may revise existing tasks
   - If the task file does not exist, find the source plan file from \`.speclet/plans/\` listed for that phase
   - Generate concrete, ordered tasks for the phase
   - Write the tasks to the task file path listed in the index

4. **Task format rules**:
   \`\`\`
   - [ ] **Task title** — brief description of what to do and what done looks like
   \`\`\`
   - Each task must be **atomic** — one clear unit of work
   - Each task must be **specific** — enough detail to implement without re-reading the plan
   - Tasks must be **ordered** — listed in the sequence they should be done
   - Do not duplicate tasks across phases
   - Reference the stack from \`.speclet/context.md\`
   - Respect constraints from \`.speclet/constitution.md\` (testing, architecture, quality rules)

5. **Report**: List the task files created or updated and the total task count per phase.
`
  );
}

function ccSkillImplement(): string {
  return (
    ccSkillFrontmatter(
      "speclet-implement",
      "Implement all tasks in a single phase, marking each task done as you go.",
    ) +
    `
# speclet implement

Work through every unchecked task in a single phase file, implementing each one in order and marking it \`[x]\` when complete.

## Instructions

The phase number or name to implement must be provided in the user's message (e.g., \`1\` or \`Phase 2\`).

1. **Load context**:
   - Read \`.speclet/context.md\` — project stack, conventions, and constraints
   - If \`.speclet/constitution.md\` exists and does **NOT** contain \`<!-- speclet:unfilled -->\`, read it — honour all quality rules, architecture principles, and Definition of Done
   - If \`.speclet/constitution.learned.md\` exists, read it — follow any rules in the \`## Pending Rules\` section
   - Read \`.speclet/tasks/index.md\` — the phase map

2. **Resolve the phase**:
   - Use the phase number or name from the user's message to identify the phase
   - If no phase was specified, ask the user which phase to implement and list available phases from the index
   - Find the task file path from the index (e.g., \`.speclet/tasks/phase-1-setup.md\`)
   - If the task file does not exist, stop and suggest running \`/speclet-tasks\` first

3. **Load the phase file**:
   - Read **ONLY** the requested phase task file — do not load any other phase files
   - Count and list the unchecked tasks (\`- [ ]\`)

4. **Implement tasks in order**:
   - Work through each unchecked task \`- [ ]\` sequentially
   - Implement the task following the stack in \`.speclet/context.md\` exactly
   - If a task is ambiguous, add a brief inline code comment and note the ambiguity — do not guess
   - Mark each task done immediately after completing it: change \`- [ ]\` to \`- [x]\`
   - Report progress after each task

5. **On completion**:
   - Verify all tasks in the phase are marked \`[x]\`
   - Update the phase file header with:
     \`\`\`
     Status: Complete
     Completed: <today's date>
     \`\`\`
   - Summarize what was built: files created, endpoints added, key decisions made
   - If any rules were appended to \`.speclet/constitution.learned.md\`, mention them and suggest running \`/speclet-learn\`

## Rules

- Follow the stack and conventions in \`.speclet/context.md\` exactly
- Honour all rules from \`.speclet/constitution.md\` (quality, architecture, DoD)
- Do **NOT** load or modify other phase files
- Halt and ask for guidance if a non-ambiguous blocker is encountered

## Capturing Learned Rules

If you correct a bash command, discover a project pattern, or notice something that should always be done:
→ Append it to \`.speclet/constitution.learned.md\` under \`## Pending Rules\`:

\`\`\`
### [YYYY-MM-DD] category: short-title
**Rule:** What to always do.
**Why:** What went wrong or why this matters.
\`\`\`

Categories: \`bash\`, \`pattern\`, \`architecture\`, \`testing\`, \`tooling\`
`
  );
}

function ccSkillLearn(): string {
  return (
    ccSkillFrontmatter(
      "speclet-learn",
      "Review auto-captured rules from implementation sessions and merge them into the constitution.",
    ) +
    `
# speclet learn

Review pending rules captured during implementation and decide which ones to permanently add to the project constitution.

## Instructions

1. **Check for pending rules**:
   - Read \`.speclet/constitution.learned.md\`
   - If no \`### \` entries exist under \`## Pending Rules\`, report "No pending rules" and stop

2. **Load current constitution**:
   - Read \`.speclet/constitution.md\`

3. **Review rules one at a time**:
   - Present each pending rule to the developer
   - Ask: **Keep (merge into constitution), Skip (discard), or Defer (leave for later)?**
   - Wait for the answer before showing the next rule

4. **Apply decisions**:
   - **Keep**: Add the rule to the appropriate section of \`.speclet/constitution.md\`. Create a new section if needed.
   - **Skip**: Remove the rule entry from \`.speclet/constitution.learned.md\`.
   - **Defer**: Leave the rule unchanged in \`.speclet/constitution.learned.md\`.

5. **Write files**:
   - Rewrite \`.speclet/constitution.md\` with all kept rules merged in
   - Rewrite \`.speclet/constitution.learned.md\` with only deferred rules remaining
     (if none remain, keep the file with its header and empty \`## Pending Rules\` section)

6. **Report**: Confirm how many rules were merged, skipped, and deferred.
`
  );
}

function copilotInstructions(): string {
  return `<!-- SPECLET START -->
This project uses speclet for spec-driven development.

Key speclet files:
- Project context: \`.speclet/context.md\` — read this first on every speclet task
- Ground rules: \`.speclet/constitution.md\` — read if present and filled in (no \`<!-- speclet:unfilled -->\` marker)
- Architecture map: \`.speclet/architecture.md\` — read when implementing features that touch existing modules (if present)
- Plan files: \`.speclet/plans/\` — original feature plans
- Task index: \`.speclet/tasks/index.md\` — the phase map, always use this to find phase files
- Phase tasks: \`.speclet/tasks/phase-N-*.md\` — one file per phase, load only what you need
<!-- SPECLET END -->
`;
}
